### ISSUE TITLE
Re-creation schema_version_type

### ISSUE THREAD

**Issue by YarovoyVladimir09** [yandex/pgmigrate#38] opened 2023-11-15 09:11 UTC
Hello!
After setting the base line value, pgmigrator tries to create schema_version_type. Pgmigrate was never used before setting baseline
https://github.com/yandex/pgmigrate/blob/master/doc/tutorial.md#baseline
```
File "<...>/pgmigrate-runner.py", line 504, in <module>
    main()
  File "/<...>/pgmigrate-runner.py", line 84, in main
    migrations_db_name=args.migrations_db_name,
  File "<...>/pgmigrate-runner.py", line 286, in migrate_to_revision
    command=command,
  File "<...>/pgmigrate-runner.py", line 302, in migrate
    pgmigrate.COMMANDS[args.cmd](config)
  File "<...>/pgmigrate.py", line 781, in migrate
    config.schema, config.cursor)
  File "<...>/pgmigrate.py", line 542, in _migrate_step
    _init_schema(schema, cursor)
  File "<...>pgmigrate.py", line 402, in _init_schema
    ('auto', 'manual'))
  File "<...>/python3.7/site-packages/psycopg2/extras.py", line 448, in execute
    return super(LoggingCursor, self).execute(query, vars)
psycopg2.errors.DuplicateObject: type "schema_version_type" already exists
```
What could be the cause of this problem?

**Comment by secwall** [comment] 2023-12-31 15:42
Could you provide an exact reproduction steps? Just setting baseline and running pgmigrate works so I'm not able to reproduce observed behaviour.

**Comment by secwall** [comment] 2024-02-19 14:49
No reproduction steps were provided so I'm closing this.

**Closed as completed by secwall** 2024-02-19 14:49 UTC
